### ISSUE TITLE
Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper

### ISSUE THREAD

**Issue by x1p** [pl3xgaming/Pictures#1]
I tried this plugin and got an error I wanted to share.
I tried a random picture form the internet. For example:
`/pictures create http://icons.iconarchive.com/icons/hydrattz/multipurpose-alphabet/64/Letter-P-blue-icon.png`
```
[14:48:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pictures' in plugin Pictures v1.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-641]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-641]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-641]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-641]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_212]
at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_212]
at java.awt.Image.getScaledInstance(Image.java:178) ~[?:1.8.0_212]
at net.pl3x.bukkit.pictures.picture.PictureManager.downloadImage(PictureManager.java:32) ~[?:?]
at net.pl3x.bukkit.pictures.command.CmdPictures.onCommand(CmdPictures.java:62) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-641]
... 15 more
```
Executing the second time, the picture appears as normal. It can be placed on a item frame.
When the server reboots, this appears at startup:
```
[15:01:15 INFO]: [Pictures] Enabling Pictures v1.0
[15:01:16 ERROR]: Error occurred while enabling Pictures v1.0 (Is it up to date?)
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_212]
at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_212]
at java.awt.Image.getScaledInstance(Image.java:178) ~[?:1.8.0_212]
at net.pl3x.bukkit.pictures.picture.PictureManager.loadImage(PictureManager.java:42) ~[?:?]
at net.pl3x.bukkit.pictures.picture.PictureManager.loadPictures(PictureManager.java:84) ~[?:?]
at net.pl3x.bukkit.pictures.Pictures.onEnable(Pictures.java:21) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-641]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-641]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-641]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-641]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-641]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-641]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[15:01:16 INFO]: [Pictures] Disabling Pictures v1.0
```
The picture is disappeared in game

Paper 1.13.2 build 641
Pictures build 7

**Comment by electronicboy** [comment]
This is down to your server environment, (seemingly) relevant bug report on launchpad here: https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1788250

**Comment by x1p** [comment]
Ok, I'll have to see what I can do about that...
